### ISSUE TITLE
Swipe display incomplete in a list when rotating device 

### ISSUE THREAD

**Issue by StephaneColson** [linagora/awesome-angular-swipe#19]
- Process a swipe left on OpenPaaS (Android, or iOS) Unified Inbox with the smartphone in portrait mode (see portraitSwipeAction1.png)

![portraitswipeaction1](https://cloud.githubusercontent.com/assets/1481595/15824662/90910678-2c00-11e6-8e6f-81f66327c4a6.png)
- Rotate the screen in order to be in landscape mode (see landscapeSwipeAction2.png)
- The swipe (orange) is not displayed completely NOK

![landscapeswipeaction2](https://cloud.githubusercontent.com/assets/1481595/15824663/90924380-2c00-11e6-97a7-133b07c4f4ef.png)

**Comment by dbenchi** [comment]
Thanks for reporting this bug. I will take care of it once I have time (but for sure in the near-future)

**Comment by dbenchi** [comment]
Fixed #19 fix swipe on rotation
